---
- name: Install ARM Prerequisites
  become: true
  when:
    - ansible_facts['distribution'] == "Ubuntu"
  apt:
    name:
      - lsscsi
      - software-properties-common
      - mkvtoolnix
      - mediainfo
    state: latest
    update_cache: true

- name: Add the '{{ arm_username }}' System User
  become: true
  ansible.builtin.user:
    name: "{{ arm_username }}"
    comment: Automatic Ripping Machine System User
    uid: "{{ arm_user_uid }}"
    groups: "{{ arm_user_groups }}"
    create_home: true
    append: true
  register: arm_user_info

- name: Setup Media Directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ arm_username }}"
    group: "{{ arm_user_group }}"
  loop:
    - "{{ arm_user_info.home }}"
    - "{{ arm_user_info.home }}/logs"
    - "{{ arm_user_info.home }}/music"
    - "{{ arm_user_info.home }}/media"
    - "{{ arm_user_info.home }}/config"

- name: Setup Install Script Directory
  file: 
    path: "{{ arm_docker_setup_script_install_dir }}"
    state: directory

- name: Download ARM Installer
  get_url:
    url: "{{ arm_docker_setup_script_url }}"
    dest: "{{ arm_docker_setup_script_install_path }}"
    mode: +x

- name: Install ARM(Docker)
  become: true
  script:
    cmd: "{{ arm_docker_setup_script_install_path }}"

- name: Enable Running Docker as '{{ arm_username }}'
  become: true
  community.general.sudoers:
    name: "{{ arm_username }}"
    group: "{{ arm_user_group }}"
    host: "{{ arm_hostname }}"
    commands: "{{ docker_bin }}"
