---
- name: Install EPEL
  become: yes
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"
  dnf:
    name:
      - epel-release
    state: latest

- name: Install Docker
  import_tasks: install-docker.yml
